version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_video_encoder
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./outputs:/app/outputs
      - ./thumbnails:/app/thumbnails
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: tg_bot_mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
